### ISSUE TITLE
Instructions and comparison

### ISSUE THREAD

**Issue by AntonisCSt** [RooTender/augmentator#21]
Hey, congratulations on this tool, It looks very nice!

I would really like to use it, however, I could not find the Instructions. Are you planning to add them?

It would also be cool to mention the advantages of other tools.

**Comment by RooTender** [comment]
Hey, glad you like the concept. When it comes to installation it's pretty straightforward, but surely I can add it. In the releases section there's a list of binaries that are available (Linux / MacOS / Windows) and the point is to just pick the one you need :)

| Releases | List of binaries to download |
|---|---|
|![image](https://github.com/RooTender/augmentator/assets/24989290/6ff3c282-7ff7-410c-bfa3-47710e84ff01)| ![image](https://github.com/RooTender/augmentator/assets/24989290/2ec51785-5f7e-4413-91e6-8904ffd4231d) |

Not sure if that's what you've meant by installation though.

Also, it's hard to actually compare this tool with others because most out there what I found are libraries. They're great, but they require people to implement them to get the desired augmentation. The goal of this tool was to remove that stage and just have something to pick the transformations you want, several clicks and you have it.

EDIT: Actually, I found one tool that I could refer to called [image_augmentor](https://github.com/codebox/image_augmentor). I'll add it, thanks for the idea c:

**Comment by AntonisCSt** [comment]
Great thanks, I think it would be valuable to add this as an instruction to the readme!

Regarding the comparison, now I better understand, and sounds indeed good! I think it would be valuable to put what you just explained in a 'Motivation' in the Readme :D for others to see. 

 Thanks again! (if you want I can close this issue).
